[font]
size = 14.0

# [[keyboard.bindings]]
# chars = "\u001B[D"
# key = "H"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001B[B"
# key = "J"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001B[A"
# key = "K"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001B[C"
# key = "L"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001B[3~"
# key = "X"
# mods = "Control"

# [window]
# decorations = "none"
# startup_mode = "fullscreen"

# [window.padding]
# x = 0
# y = 0
